### ISSUE TITLE
 ᱰᱷᱮᱨ ᱡᱟᱭᱜᱟ ᱨᱮᱜᱮ  d = ᱰ ᱦᱟᱹᱡᱩᱜ ᱠᱟᱱᱟ᱾

### ISSUE THREAD

**Issue by Prasanta-Hembram** [Prasanta-Hembram/Latin2OlChiki-Converter#1]
ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ *ᱵᱚᱫᱤ ᱵᱟᱥᱠᱤ* ᱠᱷᱚᱵᱚᱨ ᱞᱮᱫᱟᱭ ᱺ 

d = ᱫ
ᱟᱫᱚᱢ ᱴᱷᱮᱱ ᱫᱚ ᱴᱷᱤᱠ ᱜᱮ ᱦᱤᱡᱩᱜ ᱠᱟᱱᱟ ᱢᱮᱱᱠᱷᱟᱱ ᱰᱷᱮᱨ ᱡᱟᱭᱜᱟ ᱨᱮᱜᱮ 
d = ᱰ ᱦᱟᱹᱡᱩᱜ ᱠᱟᱱᱟ᱾

ᱦᱚᱞ ᱺ

**Comment by BodiBaski** [comment]
ᱦᱳᱭ,
ᱨᱳᱢᱟᱱ ᱛᱮ ᱠᱷᱟᱹᱞᱤ D/d = ᱫ ᱜᱮ ᱦᱩᱭᱩᱜᱼᱟ᱾
D/d = ᱰ ᱫᱟ ᱵᱟᱝ ᱦᱩᱭᱩᱜᱼᱟ᱾

**Comment by Prasanta-Hembram** [comment]
https://github.com/Prasanta-Hembram/Latin2OlChiki-Converter/commit/b0ba3a52be0ae224995e422fc49e95bf0d2bfcc4 ᱞᱮᱠᱟᱛᱮ ᱱᱚᱶᱟ issue ᱨᱟᱭᱟᱜ ᱦᱚᱞ ᱦᱩᱭᱮᱱᱟ ᱾ ᱱᱤᱛᱚᱜ ᱵᱚᱫᱤ ᱚᱱᱟ ᱣᱮᱵᱽᱥᱟᱭᱤᱴ ᱠᱷᱩᱞᱟᱹ ᱠᱟᱛᱮ ᱧᱮᱞ ᱢᱮ ᱾ 

ᱟᱨᱦᱚᱸ ᱡᱟᱦᱟᱸᱱᱟᱜ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱠᱷᱚᱵᱚᱨ ᱠᱷᱟᱱ ᱢᱤᱫᱴᱟᱹᱝ ᱱᱟᱶᱟ issue ᱠᱷᱩᱞᱟᱹᱭ ᱛᱟᱞᱟᱝ ᱢᱮ ᱾

**Comment by Prasanta-Hembram** [comment]
ᱦᱚᱞ ᱦᱩᱭᱮᱱᱟ ᱾
