### ISSUE TITLE
mo̠ńj ᱫᱚ exception ᱨᱮ ᱫᱚᱦᱚ

### ISSUE THREAD

**Issue by BodiBaski** [Prasanta-Hembram/Latin2OlChiki-Converter#3]
ᱱᱤᱛ "mo̠ńj = ᱢᱚᱧᱡ" ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ, ᱢᱮᱱᱠᱷᱟᱱ ᱥᱟᱱᱛᱟᱲᱤ ᱨᱮᱫᱚ "ᱢᱚᱸᱡᱽ" ᱞᱮᱠᱟᱛᱮ ᱚᱞᱚᱜᱼᱟ᱾ 
ᱚᱱᱟᱛᱮ exception ᱠᱟᱛᱮ "mo̠ńj = ᱢᱚᱸᱡᱽ" ᱠᱟᱜ ᱨᱮᱭᱟᱜ ᱱᱮᱦᱚᱨ ᱛᱟᱸᱦᱮᱱ ᱠᱟᱱᱟ᱾

**Comment by Prasanta-Hembram** [comment]
ᱵᱚᱫᱤ ᱤᱧ mo̠ńj ᱫᱚ exception ᱨᱮ ᱫᱚᱦᱚ ᱠᱟᱹᱫᱟᱹᱧ ᱾ https://github.com/Prasanta-Hembram/Latin2OlChiki-Converter/commit/a1eb8fdd638b7f8a70295395f0acd5ae9ace7f01
